### ISSUE TITLE
新版

### ISSUE THREAD

**Issue by mshjz** [mainite/VideoSlim#1]
最新版本是必须要下载python才行吗？老哥

**Comment by nana123126** [comment]
> 最新版本是必须要下载python才行吗？老哥

我下载的最新释放包(v1.2)中没有 exe 可执行文件，而v1.1.0含有 exe 可执行文件。如果你不知道该怎么使用v1.2，尝试使用v1.1.0 ，在[视频](www.bilibili.com/video/BV16M411K7jK)中可以看到up主演示的是 exe 可执行文件的操作流程。

**Comment by DongGuoZheng** [comment]
感谢反馈，安装包已上传
