### ISSUE TITLE
压缩后没有生成文件

### ISSUE THREAD

**Issue by Linjianfengccc** [mainite/VideoSlim#2]
https://github.com/mainite/VideoSlim/assets/49085765/6ba364a5-a843-43e0-ac7d-ce1eb6f501cb

如视频所示，有什么好办法能看到报错信息或者debug一下吗

**Comment by DongGuoZheng** [comment]
请问用的是1.3还是1.2方便把视频文件发给我测试下吗

**Comment by Linjianfengccc** [comment]
@mainite 安装包是2023-12-03下载的，应该是1.2
视频文件：https://drive.google.com/file/d/1abRfda55-GrJUp-3EmpEM0AuEaSrLwEP/view?usp=sharing

**Comment by Linjianfengccc** [comment]
补充：当勾选完成后删除文件，原文件被删除，目标文件没有生成
升级至1.3也一样的问题

**Comment by DongGuoZheng** [comment]
找到原因了，原因是原视频没有音频轨道，导致出现bug，我会在1.4版本解决这个问题，感谢反馈 @Linjianfengccc
