### ISSUE TITLE
[需求建议]两条关于静默选项以及进度反馈的建议

### ISSUE THREAD

**Issue by 2455DD** [mainite/VideoSlim#3]
感谢你的开源工具，比较方便，但有几点建议希望可以参考一下。

1. 是否可以添加"不跳出CMD窗口"（即静默）选项的开关，避免在多文件批量处理时反复创建和关闭窗口导致的焦点变换影响使用
2. 是否可以添加一个进度条，或是在主窗口添加一个类似"[current_idx/total_num] cur_filename" 的提示文本框以告知当前已完成的进度

**Comment by DongGuoZheng** [comment]
非常感谢你的贡献！这个修改对项目非常有帮助。🙏
