### ISSUE TITLE
config引入

### ISSUE THREAD

**Issue by w243420707** [mainite/VideoSlim#5]
--crf 23.5 --preset 8 -I 600 -r 4 -b 3 --me umh -i 1 --scenecut 60 -f 1:1 --qcomp 0.5 --psy-rd 0.3:0 --aq-mode 2 --aq-strength 0.8 -o ".\old_vtemp.mp4" %1
这个命令使用了 x264 软件，将 %1 所指代的视频文件（格式未知）编码为 H.264 格式的视频，并且将输出保存在当前目录下的名为 old_vtemp.mp4 的 MP4 文件中。具体的编码参数如下：

这部分内容是否可以做一个config，修改exe执行文件还是比较不方便

谢大佬

**Comment by mainite** [comment]
我没太理解你的意思，config用来配置哪些东西呢？🤔

**Comment by DongGuoZheng** [comment]
感谢 @FishCat233 为项目做出的贡献 #6

**Comment by w243420707** [comment]
> 我没太理解你的意思，config用来配置哪些东西呢？🤔

-crf 23.5 --preset 8 -I 600 -r 4 -b 3 --me umh -i 1 --scenecut 60 -f 1:1 --qcomp 0.5 --psy-rd 0.3:0 --aq-mode 2 --aq-strength 0.8

配置这些参数的呀

**Comment by w243420707** [comment]
谢大佬，看到更新啦
